<?php

class SI_Widget_Text extends WP_Widget
{
  public function __construct() //$id_base, $name, $widget_options = array(), $control_options = array()
  {
    parent::__construct(
      'si_widget_text',
      'SportIsland - Текстовый виджет',
      [
        'name' => 'SportIsland - Текстовый виджет',
        'description' => 'Выводит простой текст без верстки',
      ]);
  }

  public function form($instance)
  {
    ?>

    <p>
      <label for="<?= $this->get_field_id('id-text'); ?>">Введите текст:</label>
      <textarea
          id="<?= $this->get_field_id('id-text'); ?>"
          type="text"
          name="<?= $this->get_field_name('text') ?>"
          value="<?= $instance['text']; ?>"
          class="widefat"
      >
        <?= $instance['text']; ?>
      </textarea>
    </p>

    <?php

    //return parent::form($instance); // TODO: Change the autogenerated stub
  }

  public function widget($args, $instance)
  {
    echo apply_filters('si_widget_text',$instance['text']);
    //parent::widget($args, $instance); // TODO: Change the autogenerated stub
  }

  public function update($new_instance, $old_instance)
  {
    return parent::update($new_instance, $old_instance); // TODO: Change the autogenerated stub
  }
}